// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/games": {
    params: {};
  };
  "/games/:gameId": {
    params: {
      "gameId": string;
    };
  };
  "/login": {
    params: {};
  };
  "/login/verify": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/add-game": {
    params: {};
  };
  "/admin/games/:gameId": {
    params: {
      "gameId": string;
    };
  };
  "/admin/games/:gameId/edit": {
    params: {
      "gameId": string;
    };
  };
  "/admin/games/:gameId/resources/:resourceId": {
    params: {
      "gameId": string;
      "resourceId": string;
    };
  };
  "/admin/games/:gameId/resources/:resourceId/attachments/:attachmentId": {
    params: {
      "gameId": string;
      "resourceId": string;
      "attachmentId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/games" | "/games/:gameId" | "/login" | "/login/verify" | "/admin" | "/admin/add-game" | "/admin/games/:gameId" | "/admin/games/:gameId/edit" | "/admin/games/:gameId/resources/:resourceId" | "/admin/games/:gameId/resources/:resourceId/attachments/:attachmentId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/games.tsx": {
    id: "routes/games";
    page: "/games";
  };
  "routes/games.$gameId.tsx": {
    id: "routes/games.$gameId";
    page: "/games/:gameId";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/login.verify.tsx": {
    id: "routes/login.verify";
    page: "/login/verify";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/admin.add-game.tsx": {
    id: "routes/admin.add-game";
    page: "/admin/add-game";
  };
  "routes/admin.games.$gameId.tsx": {
    id: "routes/admin.games.$gameId";
    page: "/admin/games/:gameId";
  };
  "routes/admin.games.$gameId.edit.tsx": {
    id: "routes/admin.games.$gameId.edit";
    page: "/admin/games/:gameId/edit";
  };
  "routes/admin.games.$gameId.resources.$resourceId.tsx": {
    id: "routes/admin.games.$gameId.resources.$resourceId";
    page: "/admin/games/:gameId/resources/:resourceId";
  };
  "routes/admin.games.$gameId.resources.$resourceId.attachments.$attachmentId.tsx": {
    id: "routes/admin.games.$gameId.resources.$resourceId.attachments.$attachmentId";
    page: "/admin/games/:gameId/resources/:resourceId/attachments/:attachmentId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/games": typeof import("./app/routes/games.tsx");
  "routes/games.$gameId": typeof import("./app/routes/games.$gameId.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/login.verify": typeof import("./app/routes/login.verify.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin.add-game": typeof import("./app/routes/admin.add-game.tsx");
  "routes/admin.games.$gameId": typeof import("./app/routes/admin.games.$gameId.tsx");
  "routes/admin.games.$gameId.edit": typeof import("./app/routes/admin.games.$gameId.edit.tsx");
  "routes/admin.games.$gameId.resources.$resourceId": typeof import("./app/routes/admin.games.$gameId.resources.$resourceId.tsx");
  "routes/admin.games.$gameId.resources.$resourceId.attachments.$attachmentId": typeof import("./app/routes/admin.games.$gameId.resources.$resourceId.attachments.$attachmentId.tsx");
};